CREATE TABLE IF NOT EXISTS energy (
    id SERIAL PRIMARY KEY,
    station INTEGER NOT NULL,
    date_utc DATE NOT NULL,
    time_utc TIMESTAMPZ NOT NULL,
    band_22s_plus_cm2 DOUBLE PRECISION,
    band_22s_plus_dir DOUBLE PRECISION,
    band_22_18s_cm2 DOUBLE PRECISION,
    band_22_18s_dir DOUBLE PRECISION,
    band_18_16s_cm2 DOUBLE PRECISION,
    band_18_16s_dir DOUBLE PRECISION,
    band_16_14s_cm2 DOUBLE PRECISION,
    band_16_14s_dir DOUBLE PRECISION,
    band_14_12s_cm2 DOUBLE PRECISION,
    band_14_12s_dir DOUBLE PRECISION,
    band_12_10s_cm2 DOUBLE PRECISION,
    band_12_10s_dir DOUBLE PRECISION,
    band_10_8s_cm2 DOUBLE PRECISION,
    band_10_8s_dir DOUBLE PRECISION,
    band_8_6s_cm2 DOUBLE PRECISION,
    band_8_6s_dir DOUBLE PRECISION,
    band_6_2s_cm2 DOUBLE PRECISION,
    band_6_2s_dir DOUBLE PRECISION
);
